function init(self)
	msg.post(".","acquire_input_focus")
	
end		

function on_input(self, action_id, action)
	if action_id == hash("fire") and action.pressed and gui.pick_node(gui.get_node("play"), action.x, action.y)  then
		msg.post(".","start_level")
	end
	
	if action_id == hash("fire") and action.pressed and gui.pick_node(gui.get_node("exit"), action.x, action.y)  then
		msg.post("@system:", "exit", {code = 0})
	end
end
